language: node_js

node_js:
  - '8'

sudo: enabled

notifications:
  email: false

before_install:
  - npm update

install:
  - npm install

script:
  - jest --clearCache --updateSnapshot
  - npm test -- -u

cache:
  directories:
    - node_modules
